service: functions

frameworkVersion: '3'
useDotenv: true

package:
  individually: true

provider:
  name: aws
  runtime: nodejs16.x
  region: us-west-1

functions:
  initUser:
    handler: manageUsers/index.initUser

plugins:
  - serverless-plugin-typescript
  - serverless-offline
