-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."users" add column "formatting" jsonb
--  not null default '{ "fontScale": "md" }';
