-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."users" add column "auto_collapse_header" boolean
--  not null default 'false';
